In [1]:
import pandas as pd 
import numpy as np

In [34]:
df1=pd.read_csv('datasets/cars1.csv')
df2=pd.read_csv('datasets/cars2.csv')
print((df1).head())
print((df2).head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

In [36]:
df1=df1.loc[:,'mpg':'car']
df1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

In [37]:
print(df1.shape)
print(df2.shape)

(198, 9)
(200, 9)

In [45]:
my_cars=df1.append(df2)
my_cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe
183,36.0,4,107,75,2205,14.5,82,3,honda accord
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla
185,38.0,4,91,67,1965,15.0,82,3,honda civic
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto)
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx
188,25.0,6,181,110,2945,16.4,82,1,buick century limited
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion
191,22.0,6,232,112,2835,14.7,82,1,ford granada l
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

In [46]:
car_owners=np.random.randint(15000 , 73000,size=398)
car_owners

array([63218, 18151, 58327, 64333, 56940, 62509, 31870, 50911, 29853,
       16316, 68342, 32372, 32687, 68206, 55139, 18653, 26677, 58556,
       50589, 54287, 72199, 44685, 48342, 25655, 63433, 24036, 65245,
       56822, 71597, 32303, 22997, 66115, 54307, 21732, 45291, 34885,
       62302, 28391, 58107, 50909, 47148, 32456, 59032, 25621, 65257,
       71406, 55879, 23948, 36042, 59903, 21851, 48561, 29013, 56954,
       21933, 32925, 35072, 21244, 61476, 62550, 62272, 41504, 25487,
       68515, 29801, 63823, 59367, 23015, 25965, 32292, 66264, 45293,
       23797, 30854, 40761, 58509, 23203, 21277, 61324, 42164, 70249,
       41080, 53498, 34545, 24580, 29089, 20154, 50427, 46576, 68940,
       44966, 22703, 40848, 40457, 25432, 69981, 43222, 15625, 39356,
       54382, 29452, 21117, 63316, 26177, 59662, 37905, 52169, 29017,
       28908, 24788, 46300, 66847, 31448, 23908, 18719, 30972, 60063,
       21457, 62829, 25244, 71664, 44647, 62817, 59730, 50985, 61013,
       35384, 63738, 33915, 43164, 26425, 49802, 23572, 35422, 31757,
       51719, 39941, 49171, 53429, 32510, 48087, 26413, 37777, 52222,
       25507, 31401, 40338, 59926, 40190, 45837, 67025, 53612, 20486,
       33505, 49932, 52878, 68606, 17340, 38406, 30980, 60216, 39046,
       36519, 70101, 16452, 23973, 34813, 61518, 29087, 39422, 68141,
       65882, 45410, 63580, 26114, 55070, 53161, 35490, 68039, 52799,
       42225, 18609, 50170, 68306, 69109, 27764, 67493, 37395, 15091,
       19221, 15953, 51636, 16652, 21157, 36468, 30927, 61530, 24146,
       62070, 47336, 51056, 24968, 27523, 46263, 65291, 64944, 56245,
       69306, 18845, 54871, 20549, 49807, 24114, 46474, 66427, 66581,
       58201, 56821, 23736, 31981, 40901, 48647, 46997, 67249, 19920,
       32837, 33051, 19818, 67702, 35074, 31058, 46739, 42392, 70543,
       49507, 30172, 50104, 18495, 38424, 72109, 32565, 64195, 23927,
       31288, 17849, 60756, 45768, 45563, 31366, 45719, 59021, 47531,
       37046, 39905, 56544, 27847, 72941, 53972, 32710, 64395, 33872,
       65397, 51403, 52480, 38198, 53860, 66587, 50703, 23799, 20777,
       50794, 26910, 68163, 58414, 63694, 48081, 16033, 16137, 54128,
       46926, 43389, 31309, 71012, 46164, 67952, 45285, 22482, 43658,
       37546, 20895, 42487, 67629, 33687, 46328, 24228, 59024, 19776,
       25009, 69491, 17293, 15017, 33898, 43236, 31770, 19081, 67388,
       18343, 19040, 21980, 21688, 72092, 64280, 18322, 50585, 36695,
       25448, 45833, 48220, 56340, 42456, 50014, 63077, 51402, 18340,
       57606, 42186, 67408, 24837, 71752, 58794, 52818, 56184, 30175,
       30095, 40639, 44643, 18376, 48677, 23294, 44245, 49822, 49819,
       15865, 62459, 69850, 28834, 23473, 35334, 29450, 58056, 44940,
       63743, 64226, 52389, 30012, 72487, 56595, 56854, 39923, 22867,
       30752, 41653, 20582, 45065, 25288, 41851, 44450, 65066, 34669,
       37579, 56072, 62232, 25829, 51314, 28402, 37660, 72231, 42495,
       42830, 52484, 50187, 65109, 40340, 48864, 17772, 46109, 36451,
       22984, 71464, 16510, 52965, 64420, 36742, 28252, 57103, 58223,
       61175, 69099])

In [50]:
my_cars['owners']=car_owners
my_cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,63218
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,18151
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,58327
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,64333
4,17.0,8,302,140,3449,10.5,70,1,ford torino,56940
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,62509
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,31870
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,50911
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,29853
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,16316
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,68342
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,32372
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,32687
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),68206
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,55139
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,18653
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,26677
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,58556
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,50589
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,54287
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,72199
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,44685
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,48342
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,25655
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,63433
25,10.0,8,360,215,4615,14.0,70,1,ford f250,24036
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,65245
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,56822
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,71597
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,32303
...,...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,34669
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,37579
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,56072
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se,62232
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,25829
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,51314
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl,28402
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,37660
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,72231
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,42495
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,42830
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,52484
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,50187
183,36.0,4,107,75,2205,14.5,82,3,honda accord,65109
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla,40340
185,38.0,4,91,67,1965,15.0,82,3,honda civic,48864
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),17772
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,46109
188,25.0,6,181,110,2945,16.4,82,1,buick century limited,36451
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),22984
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,71464
191,22.0,6,232,112,2835,14.7,82,1,ford granada l,16510
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,52965
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,64420
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,36742
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,28252
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,57103
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,58223
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,61175
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,69099